### ISSUE TITLE
Development of a Voting UI based on React UI-components

### ISSUE THREAD

**Issue by ferranrego** [vocdoni/bounties#1]
Title | Development of a Voting UI based on React UI-components
-- | --
Short description |  The purpose of this task is to create a complete UI for an entire voting process flow using Vocdoni SDK and React UI components
Total number of bounties | 1
Period | 2 months
Payment | in USDC
Amount | 11.000 USDC
Comments | 

## Type of bounty

- [ ]  Bug bounty
- [x]  New development
- [ ]  New feature
- [ ]  Content Creation
- [ ]  Social Media Campaign
- [ ]  Translation Bounties
- [ ]  Other

## Description
The purpose of this task is to create a complete UI for an entire voting process flow as defined in the [Vocdoni Protocol specifications](https://developer.vocdoni.io/get-started/intro#1-introduction).
It should make use of the Vocdoni SDK, the [Vocdoni UI components](https://github.com/vocdoni/ui-components) (React) and based on [Chakra UI](https://chakra-ui.com/).

**Basic Funcionalities and Views of the UI:**
- [ ]  Login View – Allows user to “authenticate” using [Rainbowkit](https://www.rainbowkit.com/)
    - [ ]  Once logged in, the user can see their connected address and logout capabilities (similar to other web3 projects showing the amount of VOC tokens)
- [ ]  List Processes View – Allows user to list the elections created, see the basic information and stop, pause and resume them
- [ ]  Create Process View – Allows user to create elections (voting processes)
    - [ ]  Allowing to add addresses using ENS (Ethereum Name Service)
    - [ ]  Alo store them in localStorage for reuse
    - [ ]  Allowing to define the weights for each address (if set) in a user-friendly way
    - [ ]  Allowing to configure an Election [as defined in the Vocdoni Protocol](https://developer.vocdoni.io/get-started/intro#23-elections).
        - [ ]  Encrypted
        - [ ]  AutoStart
        - [ ]  Interruptible
        - [ ]  Max vote overwrites
- [ ]  Vote View – Allows user to vote with their account on elections
    - [ ]  See the current weight of the voter (if set)
    - [ ]  See the current results of the voting (or a message if the election has encrypted results and is not ended)
    - [ ]  Show a link to explorer – Allows user to check their participation in the election through the [Vochain Explorer (dev)](https://dev.explorer.vote/)
- [ ]  Allowing user to upload onchain the results of an election

## **Acceptance Criteria**
* Deliverables must be designed with a simple UX/UI
* Deliverables must comply with Vocdoni Brand Guidelines, and the bounty participant will coordinate with the Vocdoni team on how to apply them
* A successful deliverable includes a functioning code repo and the relevant documentation
* Any repository created should include a detailed Readme file with relevant information on installation, development state, and usage.

## Conditions
- The bounty participant should join [Vocdoni Discord](https://chat.vocdoni.io) to coordinate with the team.
- The bounty participant should share an asynchronous update on the state of the task using Github Projects, HackMD, Notion or other tools agreed by the Vocdoni Team.

# Reward
11.000 USDC* paid to the wallet specified by the selected bounty participant
_*A total of 5000 USDC will be paid at the beginning of the project and 6000 USDC will be paid when the deliverables are complete and ready for sharing_

**Comment by gerouvi** [comment]
Hello,

I am Gerard Roura and I am glad to contribute to the project. I am willing to work with you to develop the new UI for the voting system.

I have been playing around with the Vocdoni SDK and chakra UI, and here is an experiment I have made: https://github.com/gerouvi/vuitest.git 

My Discrod handle is Gerard R#7216

Thank you
Have a good day

**Comment by ferranrego** [comment]
Hi Gerard!

Thank you for offering to help with the task. Your experience with the Vocdoni SDK and Chakra UI seems what we are looking for, so we would love to discuss further details with you in Discord! I'll send you a DM.

Cheers!

**Comment by gerouvi** [comment]
Hello Ferran,

Thank you again. Let me know when you want a talk. Looking forward to start.
